### PR TITLE
Ui changes

### LINKED ISSUE #2: Newsletter - Develop

### PR DESCRIPTION
**Pull request by shidhincr**
Minor UI updates: 

screen shot 2019-02-07 at 10 38 43 pm

All issues template:

screen shot 2019-02-08 at 9 38 57 pm

Once done, this PR closes #2

### CODE REVIEW

**Comment by shidhincr** [comment]
@gokulkrishh I think it's better to keep the home page as the latest issue content. And, we can provide the link to browse for the old issues. Wdyt ??

**Comment by gokulkrishh** [comment]
@shidhincr Sounds good. So home page will be having latest issue and back button will go back to full issues list ??

**Comment by gokulkrishh** [comment]
@shidhincr Some minor feedback 🤓on UI

1. Header with issue #1 and date now have more height (Gradient line and content). Can we reduce some ?
2. Can we add some border-radius to issue white background ?

**Comment by shidhincr** [comment]
@gokulkrishh  Thanks man..

1. Will remove the extra spacing.
2. I have added a box shadow to the inner box -- isn't that visible?
3. I gave a light color for the website url.. I guess that was not enough to feel the distinction. Let's try a different color

Btw, we need to create another issue for the layout of All issues template.

**Comment by gokulkrishh** [comment]
@shidhincr Cool.

for point 2, yes it is visible. May be little less visible in screenshot. Let's go with it. No change needed for this.

Regarding **all issues**:

It will be similar layout one columns with list of issues like 

------------------------------------------------------------
Issue #1 
Date
------------------------------------------------------------
Issue #2
Date
------------------------------------------------------------

separated by a border. Let's stick to this simple one

**Comment by shidhincr** [comment]
👍

**Pull request merged**
